name: pretest_posttest_app
description: "Frontend Flutter Pre-Test & Post-Test Dasar Python (UI only, no backend)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Italic-Variable.ttf
          weight: 400
          style: italic
